const PRICE_DATE = 'September 2026';

const CATEGORIES = [
  { id:'wasser', name:'Tafelwasseranlagen', short:'Tafelwasser', img:'w_mf20',
    lead:'Festwasseranschluss, alle Geräte mit stillem, gekühltem und sprudelndem Wasser. Made in Italy.',
    metricLabel:'Kühlleistung', tabs:['sets','check'] },
  { id:'bottle', name:'Wasserspender mit Bottles', short:'Bottles', img:'b_fmax',
    lead:'Ohne feste Wasserleitung. Steckdose reicht, Wasser kommt in 18,9-Liter-Bottles von ewatec H2O.',
    metricLabel:'Kälte' },
  { id:'kaffee', name:'Kaffeevollautomaten', short:'Kaffee', img:'k_g500',
    lead:'Vom kompakten Bürogerät bis zum Self-Service-Automaten mit Becherausgabe und Bezahlsystem.',
    metricLabel:'Tassen pro Tag' },
  { id:'barista', name:'Siebträger & Mühlen', short:'Siebträger', img:'gg_gt7_life',
    lead:'Gaggia Milano Siebträgermaschinen für Gastronomie, Bäckerei und Hotel, dazu Mühlen und Stampfer.',
    metricLabel:'Gruppen' },
  { id:'vending', name:'Warenautomaten', short:'Automaten', img:'v_gsnack',
    lead:'SandenVendo Snack-, Getränke-, Tiefkühl- und Kaffeeautomaten für innen und außen.',
    metricLabel:'Auswahlen' }
];

/* ---------- Filter pro Kategorie ---------- */
const FILTERS = {
  wasser: [
    { key:'bau', label:'Bauform', opts:[
      ['Auftisch', p=>p.group==='Auftischgerät'], ['Standgerät', p=>p.group==='Standgerät'],
      ['Untertisch', p=>p.group==='Untertischgerät'], ['Küchen-Set', p=>p.group==='Küchen-Set'||p.group==='Komplettset'],
      ['Zapfhahn', p=>p.group==='Zapfhahn'] ]},
    { key:'lh', label:'Kühlleistung', opts:[
      ['bis 20 l/h', p=>p.num!=null&&p.num<=20], ['30 bis 45 l/h', p=>p.num>=30&&p.num<=45], ['80 l/h', p=>p.num>=80] ]},
    { key:'hot', label:'Heißwasser', opts:[ ['mit Heißwasser', p=>p.water.includes('heiss')], ['ohne', p=>!p.water.includes('heiss')] ]},
    { key:'brand', label:'Hersteller', vertrieb:true, opts:[ ['GWS', p=>p.brand==='GWS'], ['Blupura', p=>p.brand==='Blupura'], ['Celli', p=>p.brand==='Celli'] ]},
    { key:'price', label:'Preis', vertrieb:true, opts:[ ['bis 2.000 €', p=>p.price!=null&&p.price<=2000], ['2.000 bis 2.600 €', p=>p.price>2000&&p.price<=2600], ['über 2.600 €', p=>p.price>2600] ]}
  ],
  bottle: [
    { key:'spr', label:'Wasserarten', opts:[ ['mit Sprudel', p=>p.water.includes('sprudel')], ['still und gekühlt', p=>!p.water.includes('sprudel')] ]}
  ],
  kaffee: [
    { key:'bau', label:'Bauform', opts:[ ['Tischgerät', p=>p.group==='Tischgerät'], ['Standautomat mit Becher', p=>p.group==='Standautomat'] ]},
    { key:'cups', label:'Tassen pro Tag', opts:[ ['bis 100', p=>p.num<=100], ['100 bis 200', p=>p.num>100&&p.num<=200], ['über 200', p=>p.num>200] ]}
  ],
  barista: [
    { key:'typ', label:'Gerät', opts:[ ['Siebträger', p=>p.group==='Siebträger'], ['Mühle', p=>p.group==='Mühle'], ['Stampfer', p=>p.group==='Stampfer'] ]},
    { key:'grp', label:'Gruppen', opts:[ ['1-gruppig', p=>p.num===1&&p.group==='Siebträger'], ['2-gruppig', p=>p.num===2&&p.group==='Siebträger'], ['3-gruppig', p=>p.num===3&&p.group==='Siebträger'] ]},
    { key:'serie', label:'Baureihe', opts:[ ['GT3', p=>p.line==='GT3'], ['GT7', p=>p.line==='GT7'], ['La Nera', p=>p.line==='La Nera'], ['La Vetro', p=>p.line==='La Vetro'], ['La Vetro Pro', p=>p.line==='La Vetro Pro'] ]},
    { key:'tall', label:'Tall Cup', opts:[ ['Tall Cup', p=>/tall/i.test(p.name)] ]},
    { key:'price', label:'Preis', vertrieb:true, opts:[ ['bis 4.000 €', p=>p.price!=null&&p.price<=4000], ['4.000 bis 6.000 €', p=>p.price>4000&&p.price<=6000], ['über 6.000 €', p=>p.price>6000] ]}
  ],
  vending: [
    { key:'ware', label:'Ware', opts:[ ['Snacks', p=>p.tags.includes('snack')], ['Getränke', p=>p.tags.includes('drink')], ['Tiefkühl', p=>p.tags.includes('frozen')], ['Heißgetränke', p=>p.tags.includes('kaffee')], ['Non-Food', p=>p.tags.includes('nonfood')] ]},
    { key:'ort', label:'Standort', opts:[ ['Indoor', p=>p.tags.includes('indoor')], ['Outdoor', p=>p.tags.includes('outdoor')] ]}
  ]
};

/* ---------- Geräteberater pro Kategorie ---------- */
const ADVISOR = {
  wasser: [
    { q:'Wo wird gezapft?', opts:[
      ['Theke frei', 'Gerät steht auf der Arbeitsfläche', p=>p.group==='Auftischgerät'],
      ['Keine Theke', 'Frei aufstellbares Standgerät', p=>p.group==='Standgerät'],
      ['An der Spüle', 'Untertischgerät mit Zapfhahn', p=>p.group==='Küchen-Set'||p.group==='Komplettset'] ]},
    { q:'Wie viele Personen?', opts:[
      ['bis 15', 'bis ca. 20 l/h', p=>p.num<=20],
      ['15 bis 50', '20 bis 45 l/h', p=>p.num>=20&&p.num<=45],
      ['über 50 / Kantine', 'ab 45 l/h, Self-Service', p=>p.num>=45] ]},
    { q:'Heißwasser gewünscht?', opts:[
      ['Ja', 'Tee und Instant aus einem Gerät', p=>p.water.includes('heiss')],
      ['Nein', 'Still, gekühlt, sprudelnd', p=>!p.water.includes('heiss')] ]}
  ],
  bottle: [
    { q:'Soll das Gerät sprudeln?', opts:[
      ['Ja', 'CO₂-Flasche im Gehäuse', p=>p.water.includes('sprudel')],
      ['Nein', 'Raumtemperiert und gekühlt', p=>!p.water.includes('sprudel')] ]}
  ],
  kaffee: [
    { q:'Wie viele Tassen am Tag?', opts:[
      ['bis 100', 'Kleine Büros, Praxen', p=>p.num<=100],
      ['100 bis 200', 'Mittlere Büros, Bäckerei', p=>p.num>100&&p.num<=200],
      ['über 200', 'Große Standorte, Kantine', p=>p.num>200] ]},
    { q:'Wie wird bedient?', opts:[
      ['Mit eigener Tasse', 'Tischgerät in Teeküche oder Büro', p=>p.group==='Tischgerät'],
      ['Self-Service mit Becher', 'Standautomat, Bezahlsystem möglich', p=>p.group==='Standautomat'] ]}
  ],
  barista: [
    { q:'Was wird gesucht?', opts:[
      ['Siebträger', 'Espressomaschine', p=>p.group==='Siebträger'],
      ['Mühle', 'Kaffeemühle on demand', p=>p.group==='Mühle'],
      ['Stampfer', 'Automatisches Tampen', p=>p.group==='Stampfer'] ]},
    { q:'Wie viele Gruppen?', opts:[
      ['1', 'Kleiner Betrieb, Büro', p=>p.group!=='Siebträger'||p.num===1],
      ['2', 'Café, Bäckerei', p=>p.group!=='Siebträger'||p.num===2],
      ['3', 'Hohe Frequenz', p=>p.group!=='Siebträger'||p.num===3] ]},
    { q:'Tall Cup für To-go-Becher?', opts:[
      ['Ja', 'Hohe Brühgruppe', p=>p.group!=='Siebträger'||/tall/i.test(p.name)||/Tall Cup optional/i.test(p.features.join(' '))],
      ['Nein', 'Standard-Tassen', p=>true] ]}
  ],
  vending: [
    { q:'Was soll verkauft werden?', opts:[
      ['Snacks', 'Riegel, Chips, Süßwaren', p=>p.tags.includes('snack')],
      ['Getränke', 'Dosen, PET, Glas', p=>p.tags.includes('drink')],
      ['Tiefkühl', 'Eis, Pizza, Eiswürfel', p=>p.tags.includes('frozen')],
      ['Heißgetränke', 'Kaffee im Becher', p=>p.tags.includes('kaffee')],
      ['Non-Food', 'Arbeitsschutz, Ersatzteile', p=>p.tags.includes('nonfood')] ]},
    { q:'Wo steht der Automat?', opts:[
      ['Innen', 'Pausenraum, Foyer', p=>p.tags.includes('indoor')],
      ['Außen', 'Wetterfest, beheiztes Glas', p=>p.tags.includes('outdoor')] ]}
  ]
};

/* ---------- Geräte ---------- */
const PRODUCTS = [
/* ===== TAFELWASSER · AUFTISCH ===== */
{ id:'mf10up', cat:'wasser', group:'Auftischgerät', brand:'GWS', name:'Prestigio MF 10 UP', serie:'', img:'w_mf10',
  sub:'Auftischgerät für kleine Teams', price:1603, code:'M1UPBK schwarz · M1UPWT weiß',
  water:['still','kalt','sprudel'], num:10, metric:'10 l/h',
  features:['Stilles, gekühltes und sprudelndes Wasser auf Knopfdruck','Nur 19 cm breit, passt auch in enge Teeküchen','Karbonator mit 2,2 Litern für frisches Sprudelwasser','Wahlweise in Schwarz oder Weiß'],
  specs:[['Maße B × T × H','190 × 439 × 422 mm'],['Gewicht','12 kg'],['Kühlleistung','10 l/h, ΔT 10 °C'],['Karbonator','2,2 l'],['Pumpe','Membranpumpe 24 V DC'],['Kondensation','statisch'],['Kältemittel','R1234yf'],['Leistungsaufnahme','145 W']],
  fits:'Kleine Büros, Praxen und Teeküchen bis etwa 15 Personen.',
  pitch:'Schmalstes Auftischgerät der Linie, nur 19 cm breit.',
  related:['m1of','mf20up'] },
{ id:'mf20up', cat:'wasser', group:'Auftischgerät', brand:'GWS', name:'Elegante MF 20 UP', serie:'', img:'w_mf20',
  sub:'Der Allrounder fürs Büro', price:1930, code:'M2UPBK schwarz · M2UPWT weiß',
  water:['still','kalt','sprudel'], num:20, metric:'20 l/h',
  features:['Stilles, gekühltes und sprudelndes Wasser auf Knopfdruck','Doppelte Kühlleistung gegenüber dem Prestigio','Großer 5,5-Liter-Karbonator für Spitzenzeiten','Wahlweise in Schwarz oder Weiß'],
  specs:[['Maße B × T × H','250 × 474 × 422 mm'],['Gewicht','16 kg'],['Kühlleistung','20 l/h, ΔT 12 °C'],['Karbonator','5,5 l'],['Pumpe','65 W'],['Kondensation','statisch'],['Kältemittel','R1234yf'],['Leistungsaufnahme','160 W']],
  fits:'Büros und Verwaltungen mit 15 bis 50 Personen.',
  pitch:'Meistverkauftes Format. Doppelte Kühlleistung und mehr als doppelt so großer Karbonator wie der Prestigio.',
  related:['mf20uph','m2of','mf10up'] },
{ id:'mf20uph', cat:'wasser', group:'Auftischgerät', brand:'GWS', name:'Elegante Hot MF 20 UPH', serie:'', img:'w_mf20h',
  sub:'Mit Heißwasser für Tee', price:2040, code:'MF20UPH · COD. M2HT',
  water:['still','kalt','sprudel','heiss'], num:20, metric:'20 l/h',
  features:['Stilles, gekühltes, sprudelndes und heißes Wasser aus einem Gerät','Extra heißes Wasser mit 95 °C für Tee und Instantgetränke','Spart den separaten Wasserkocher in der Teeküche','Gleiche Kühlleistung und Karbonatorgröße wie der Elegante'],
  specs:[['Maße B × T × H','250 × 474 × 435 mm'],['Gewicht','16 kg'],['Kühlleistung','20 l/h'],['Heißwasser','95 °C, Boiler 0,9 l druckbeaufschlagt'],['Karbonator','5,5 l'],['Kältemittel','R1234yf'],['Leistungsaufnahme','2.000 W']],
  fits:'Büros, die Tee und Wasser aus einem Gerät wollen.',
  pitch:'Günstigstes Heißwassergerät der Linie, nur 110 € Aufpreis zum MF 20 UP.',
  internal:'2.000 W Anschlussleistung: Steckdose und Absicherung prüfen.',
  related:['mf20up','set-kueche-hot'] },
{ id:'bs30', cat:'wasser', group:'Auftischgerät', brand:'Blupura', name:'Blusoda 30 Fizz Edelstahl', serie:'', img:'w_bs30',
  sub:'Edelstahl, stark und kompakt', price:2152.00, code:'',
  water:['still','kalt','sprudel'], num:30, metric:'30 l/h',
  features:['Robustes Edelstahlgehäuse, leicht zu reinigen','Trockenkühlung mit Edelstahl-Kühlschlange','Natürliches, klimafreundliches Kältemittel R290','Optional: Portionierung und passender Unterschrank'],
  specs:[['Maße B × T × H','261 × 499 × 418 mm'],['Gewicht','28 kg'],['Kühlleistung','30 l/h'],['Kühlung','Trockenkühlung'],['Pumpe','Membranpumpe'],['Ausschankhöhe','276 mm'],['Kältemittel','R290'],['Leistungsaufnahme','300 W']],
  fits:'Große Leistung auf wenig Platz, Büros ab 20 Personen.',
  pitch:'Edelstahl und natürliches Kältemittel R290.',
  options:[['Portion Control',297],['Unterschrank Blusoda 30',470]],
  related:['bs45'] },
{ id:'bs45', cat:'wasser', group:'Auftischgerät', brand:'Blupura', name:'Blusoda 45 Fizz Edelstahl', serie:'', img:'w_bs45',
  sub:'Edelstahl für höheren Bedarf', price:2566.00, code:'',
  water:['still','kalt','sprudel'], num:45, metric:'45 l/h',
  features:['50 % mehr Kühlleistung als der Blusoda 30','Hohe Ausschankhöhe, auch für Karaffen und Flaschen','Natürliches, klimafreundliches Kältemittel R290','Optional: Portionierung und passender Unterschrank'],
  specs:[['Maße B × T × H','318 × 499 × 470 mm'],['Gewicht','31 kg'],['Kühlleistung','45 l/h'],['Kühlung','Trockenkühlung'],['Pumpe','Membranpumpe'],['Ausschankhöhe','329 mm'],['Kältemittel','R290'],['Leistungsaufnahme','385 W']],
  fits:'Höherer Verbrauch, 30 bis 60 Personen, Besprechungsbereiche mit Karaffen.',
  pitch:'50 % mehr Kühlleistung als Blusoda 30 für 414 € Aufpreis.',
  options:[['Portion Control',297],['Unterschrank Blusoda 45',470]],
  related:['bs30','cool1'] },
/* ===== TAFELWASSER · STANDGERÄTE ===== */
{ id:'m1of', cat:'wasser', group:'Standgerät', brand:'GWS', name:'Prestigio Office M1 OF', serie:'', img:'w_m1of',
  sub:'Standgerät, keine Theke nötig', price:1956, code:'M1OFBK schwarz · M1OFWT weiß',
  water:['still','kalt','sprudel'], num:10, metric:'10 l/h',
  features:['Der Prestigio auf einem passenden Unterschrank','Frei aufstellbar: Empfang, Flur oder Pausenraum','Bequeme Entnahmehöhe von 303 mm, auch für Flaschen','Wahlweise in Schwarz oder Weiß'],
  specs:[['Maße B × T × H','250 × 500 × 1260 mm'],['Gewicht','12 kg'],['Kühlleistung','10 l/h'],['Karbonator','2,2 l'],['Pumpe','Membran 24 V DC'],['Entnahmehöhe','303 mm'],['Gehäuse','lackiertes Stahlblech'],['Leistungsaufnahme','145 W']],
  fits:'Kleine Büros ohne Thekenfläche: Empfang, Flur, Pausenraum.',
  pitch:'Technisch das MF 10 UP auf Unterschrank, dieselben Ersatzteile.',
  related:['mf10up','m2of'] },
{ id:'m2of', cat:'wasser', group:'Standgerät', brand:'GWS', name:'Elegante Office M2 OF', serie:'', img:'w_m2of',
  sub:'Der Standard ohne Thekenplatz', price:2272, code:'M2OFBK schwarz · M2OFWT weiß',
  water:['still','kalt','sprudel'], num:20, metric:'20 l/h',
  features:['Der Elegante auf einem passenden Unterschrank','Frei aufstellbar, braucht nur Wasser- und Stromanschluss','Front auf Wunsch mit Ihrem Firmenlogo','Wahlweise in Schwarz oder Weiß'],
  specs:[['Maße B × T × H','250 × 500 × 1240 mm'],['Gewicht','16 kg'],['Kühlleistung','20 l/h'],['Karbonator','5,5 l'],['Pumpe','65 W'],['Entnahmehöhe','303 mm'],['Gehäuse','lackiertes Stahlblech'],['Leistungsaufnahme','160 W']],
  fits:'Büros ab 15 Personen ohne Thekenplatz.',
  pitch:'Front mit Kundenlogo bedruckbar, schwarz oder weiß.',
  related:['mf20up','m1of','cool1'] },
{ id:'cool1', cat:'wasser', group:'Standgerät', brand:'Blupura', name:'Cool1 80 Fizz Edelstahl', serie:'', img:'w_cool1',
  sub:'Für Kantine und Produktion', price:3343.00, code:'',
  water:['still','kalt','sprudel'], num:80, metric:'80 l/h',
  features:['Stilles, gekühltes und sprudelndes Wasser in großen Mengen','Robuste Edelstahltasten, gut erreichbar','Filter und CO₂-Flasche finden mit Halterung im Gerät Platz','Optional: Portionierung für Flaschen und Karaffen'],
  specs:[['Maße B × T × H','479 × 428 × 1440 mm'],['Gewicht','42 kg'],['Kühlleistung','80 l/h'],['Kühlung','Eisbank 14 l / 5 kg'],['Pumpe','Membranpumpe'],['Ausschankhöhe','297 mm'],['Kältemittel','R290'],['Leistungsaufnahme','530 W']],
  fits:'Kantinen, Produktion und Self-Service mit über 50 Personen.',
  pitch:'Stärkstes Gerät der Linie. Tasten unten gut erreichbar, Fronttür für Wartung.',
  internal:'CO₂-Flasche bis 55 cm hoch und Ø 15 cm passt mit optionaler Halterung ins Gerät.',
  related:['bs45','m2of'] },
/* ===== TAFELWASSER · UNTERTISCH ===== */
{ id:'jclass', cat:'wasser', group:'Untertischgerät', brand:'Celli', name:'J-Class IN 30 ACWG CU', serie:'', img:'w_jclass',
  sub:'Wasser direkt aus dem Hahn', price:1810.00, code:'215636', priceNote:'ohne Hahn',
  water:['raum','kalt','sprudel'], num:30, metric:'30 l/h',
  features:['Verschwindet im Unterschrank, die Arbeitsfläche bleibt frei','Ungekühltes, gekühltes und sprudelndes Wasser aus dem Zapfhahn','Eisbank-Kühlung mit 30 Litern pro Stunde','Im Set mit Zapfhahn G100 oder Power Stream'],
  specs:[['Maße B × T × H','255 × 400 × 400 mm'],['Kühlleistung','30 l/h, davon 7 l am Stück'],['Kühlung','Eisbank 4 l / 2 kg'],['Karbonator','1 l'],['Pumpe','Rotationspumpe 100 l/h, 9 bar'],['Kondensation','belüftet'],['Wasserkreislauf','Kupfer'],['Kältemittel','R290'],['Leistungsaufnahme','350 W']],
  fits:'10 bis 50 Personen, kleine Büros, Restaurants.',
  pitch:'Plug & Play, das Gerät verschwindet im Unterschrank. Immer als Set mit Hahn anbieten.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis. Belüftete Kondensation: Luft im Schrank einplanen.',
  related:['set-kueche','set-kueche-touch','g100','ps'] },
{ id:'h2omy', cat:'wasser', group:'Untertischgerät', brand:'Celli', name:'H2OMY IN 15 CHWG', serie:'', img:'w_h2omy',
  sub:'Kalt, sprudelnd und heiß', price:1650.00, code:'215360', priceNote:'ohne Hahn',
  water:['kalt','sprudel','heiss'], num:15, metric:'15 l/h',
  features:['Gekühltes, sprudelndes und 95 °C heißes Wasser an der Spüle','Kein Gerät auf der Arbeitsfläche','Kompakt: passt in fast jeden Küchenunterschrank','Im Set mit Zapfhahn C-Tap oder Power Stream'],
  specs:[['Maße B × T × H','260 × 330 × 407 mm'],['Kühlleistung','15 l/h, davon 3 l am Stück'],['Heißwasser','13 l/h bei 95 °C, Boiler 1 l, 1.200 W'],['Kühlung','Eisbank 2 l / 1 kg'],['Karbonator','0,5 l'],['Pumpe','Membranpumpe 80 l/h, 8 bar'],['Kältemittel','R290'],['Leistungsaufnahme','1.410 W']],
  fits:'1 bis 10 Personen, kleine Teams mit Teeküche.',
  pitch:'Kalt, sprudelnd und heiß aus der Spüle. Kein ungekühltes Wasser.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis.',
  related:['set-kueche-hot','set-kueche-touch-hot','ctap','psh'] },
/* ===== TAFELWASSER · HÄHNE ===== */
{ id:'ctap', cat:'wasser', group:'Zapfhahn', brand:'Celli', name:'C-Tap ACHWG Black matt', serie:'', img:'w_ctap',
  sub:'Elektronisch, mit Heißwasser', price:1351.00, code:'123909', priceNote:'nur mit Untertischgerät',
  water:['raum','kalt','sprudel','heiss'], num:null, metric:'5-Wege-Hahn',
  features:['Elektronischer 5-Wege-Hahn mit LED-Band','Control Box inklusive','Passt zu H2OMY IN'],
  specs:[['Typ','elektronisch, 5 Wege, LED-Band'],['Maße','158 × 386 mm'],['Control Box','263 × 182 × 90 mm, 50 W, Schuko, 1,5 m'],['Anschluss','G3/8'],['Farbe','Black matt']],
  fits:'Küchen mit H2OMY IN, wenn Heißwasser an der Spüle gewünscht ist.',
  pitch:'Hähne laufen nur mit Untertischgerät, deshalb immer als Set anbieten.',
  internal:'Braucht Steckdose unter der Spüle.',
  related:['set-kueche-hot','h2omy'] },
{ id:'g100', cat:'wasser', group:'Zapfhahn', brand:'Celli', name:'G100 ACWG Black matt', serie:'', img:'w_g100',
  sub:'Mechanisch, ohne Heißwasser', price:672.00, code:'221714', priceNote:'nur mit Untertischgerät',
  water:['raum','kalt','sprudel'], num:null, metric:'5-Wege-Hahn',
  features:['Mechanischer 5-Wege-Hahn','Kein Strom am Hahn nötig','Kombinierbar mit J-Class IN und H2OMY IN'],
  specs:[['Typ','mechanisch, 5 Wege'],['Farbe','Black matt'],['Kombinierbar','J-Class IN, H2OMY IN']],
  fits:'Einstiegs-Set an der Spüle mit J-Class IN.',
  pitch:'Günstigster Hahn der Linie, kein Strom am Hahn.',
  related:['set-kueche','jclass'] },
{ id:'psh', cat:'wasser', group:'Zapfhahn', brand:'Celli', name:'Power Stream High ACHWG', serie:'', img:'w_psh',
  sub:'Touch-Display, mit Heißwasser', price:940.00, code:'123864', priceNote:'nur mit Untertischgerät',
  water:['raum','kalt','sprudel','heiss'], num:null, metric:'Touch-Hahn',
  features:['Elektronisch mit Touch-Display','Edelstahl / satiniertes Aluminium','Control Box inklusive','Portion für Glas oder Flasche wird bei der Montage eingestellt'],
  specs:[['Typ','elektronisch, Touch-Display'],['Höhe','360 mm'],['Material','Edelstahl / satiniertes Alu'],['Control Box','inklusive, Schuko']],
  fits:'Moderne Küchen mit H2OMY IN, Portionierung gewünscht.',
  pitch:'Günstiger als der C-Tap und mit Portionierung.',
  internal:'Braucht Steckdose unter der Spüle. Portion bei der Montage einstellen.',
  related:['set-kueche-touch-hot','h2omy'] },
{ id:'ps', cat:'wasser', group:'Zapfhahn', brand:'Celli', name:'Power Stream High ACWG', serie:'', img:'w_ps',
  sub:'Touch-Display, ohne Heißwasser', price:890.00, code:'123860', priceNote:'nur mit Untertischgerät',
  water:['raum','kalt','sprudel'], num:null, metric:'Touch-Hahn',
  features:['Elektronisch mit Touch-Display','Edelstahl / satiniertes Aluminium','Control Box inklusive','Portion für Glas oder Flasche wird bei der Montage eingestellt'],
  specs:[['Typ','elektronisch, Touch-Display'],['Höhe','360 mm'],['Material','Edelstahl / satiniertes Alu'],['Control Box','inklusive, Schuko']],
  fits:'Moderne Küchen mit J-Class IN, Portionierung gewünscht.',
  pitch:'Touch-Bedienung und Portionierung zum kleinen Aufpreis gegenüber G100.',
  internal:'Braucht Steckdose unter der Spüle.',
  related:['set-kueche-touch','jclass'] },
/* ===== TAFELWASSER · KOMPLETTSET & SETS ===== */
{ id:'wave', cat:'wasser', group:'Komplettset', brand:'Blupura', name:'Wave Home', serie:'', img:'w_wave', badge:'Neu 2026',
  sub:'Komplettset für die Küche, Hahn und Box', price:1700.00, code:'', priceNote:'inkl. Blutron Hero Filter',
  water:['raum','kalt','medium','sprudel'], num:12, metric:'12 l/h',
  features:['Alles in einem Set: Kühlung, Filter und CO₂-Flasche in der Box','Vier Wasserarten: ungekühlt, gekühlt, medium und sprudelnd','Portion per Doppeltipp, LED-Ring zeigt die Wassersorte','Hahn um 180° drehbar','Hahn in Chrom, Schwarz matt, Satin, Bronze oder Gold'],
  specs:[['Hahn B × T × H','164 × 233 × 425 mm, 1,6 kg'],['Box B × T × H','216 × 479 × 441 mm, 23 kg'],['Kühlleistung','12 l/h'],['Filter','Blutron Hero, in der Box'],['CO₂','Flasche in der Box'],['Display','an der Box'],['Kältemittel','R290']],
  fits:'Kleine Teams und Chefküchen, die ein hochwertiges Design an der Spüle wollen.',
  pitch:'Günstigste Lösung an der Spüle, Filter schon im Preis. Fünf Hahnfarben.',
  related:['set-kueche','set-kueche-touch-hot'] },
{ id:'set-kueche', cat:'wasser', group:'Küchen-Set', brand:'Celli', name:'Set Küche', serie:'', img:'w_g100', img2:'w_jclass',
  sub:'J-Class IN 30 + G100', price:2482.00, code:'215636 + 221714', set:[['jclass',1810],['g100',672]],
  water:['raum','kalt','sprudel'], num:30, metric:'30 l/h',
  features:['Untertischgerät J-Class IN 30 mit mechanischem Hahn G100','Ungekühlt, kalt und sprudelnd','Kein Strom am Hahn nötig'],
  specs:[['Inhalt','J-Class IN 30 ACWG CU + G100 ACWG'],['Kühlleistung','30 l/h, davon 7 l am Stück'],['Platz unter der Spüle','25,5 × 40 × 40 cm']],
  fits:'10 bis 50 Personen, Wasser direkt an der Spüle.',
  pitch:'Einstiegs-Set für die Küche.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis. Montage nicht enthalten.',
  related:['jclass','g100','set-kueche-touch'] },
{ id:'set-kueche-hot', cat:'wasser', group:'Küchen-Set', brand:'Celli', name:'Set Küche Hot', serie:'', img:'w_ctap', img2:'w_h2omy',
  sub:'H2OMY IN 15 + C-Tap', price:3001.00, code:'215360 + 123909', set:[['h2omy',1650],['ctap',1351]],
  water:['kalt','sprudel','heiss'], num:15, metric:'15 l/h',
  features:['H2OMY IN 15 mit elektronischem C-Tap','Kalt, sprudelnd und 95 °C heiß','LED-Band am Hahn'],
  specs:[['Inhalt','H2OMY IN 15 CHWG + C-Tap ACHWG'],['Kühlleistung','15 l/h, Heißwasser 13 l/h'],['Platz unter der Spüle','26 × 33 × 40,7 cm'],['Strom','Steckdose unter der Spüle']],
  fits:'Bis 10 Personen, Tee und Sprudel aus einem Hahn.',
  pitch:'Premium-Set mit Heißwasser.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis. Montage nicht enthalten.',
  related:['h2omy','ctap','set-kueche-touch-hot'] },
{ id:'set-kueche-touch', cat:'wasser', group:'Küchen-Set', brand:'Celli', name:'Set Küche Touch', serie:'', img:'w_ps', img2:'w_jclass',
  sub:'J-Class IN 30 + Power Stream ACWG', price:2700.00, code:'215636 + 123860', set:[['jclass',1810],['ps',890]],
  water:['raum','kalt','sprudel'], num:30, metric:'30 l/h',
  features:['J-Class IN 30 mit Touch-Hahn Power Stream','Ungekühlt, kalt und sprudelnd','Portionierung für Glas oder Flasche'],
  specs:[['Inhalt','J-Class IN 30 ACWG CU + Power Stream High ACWG'],['Kühlleistung','30 l/h'],['Platz unter der Spüle','25,5 × 40 × 40 cm'],['Strom','Steckdose unter der Spüle']],
  fits:'10 bis 50 Personen, moderne Küche mit Touch-Bedienung.',
  pitch:'Touch-Bedienung und Portion für 218 € mehr als das Set Küche.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis. Montage nicht enthalten.',
  related:['jclass','ps','set-kueche'] },
{ id:'set-kueche-touch-hot', cat:'wasser', group:'Küchen-Set', brand:'Celli', name:'Set Küche Touch Hot', serie:'', img:'w_psh', img2:'w_h2omy',
  sub:'H2OMY IN 15 + Power Stream ACHWG', price:2590.00, code:'215360 + 123864', set:[['h2omy',1650],['psh',940]],
  water:['kalt','sprudel','heiss'], num:15, metric:'15 l/h',
  features:['H2OMY IN 15 mit Touch-Hahn Power Stream','Kalt, sprudelnd und heiß','Portionierung für Glas oder Flasche'],
  specs:[['Inhalt','H2OMY IN 15 CHWG + Power Stream High ACHWG'],['Kühlleistung','15 l/h, Heißwasser 13 l/h'],['Platz unter der Spüle','26 × 33 × 40,7 cm'],['Strom','Steckdose unter der Spüle']],
  fits:'Bis 10 Personen, Heißwasser mit Touch-Bedienung.',
  pitch:'Heißwasser an der Spüle, 411 € günstiger als das Set Küche Hot.',
  internal:'Filter, Wasser- und CO₂-Druckminderer nicht im Preis. Montage nicht enthalten.',
  related:['h2omy','psh','set-kueche-hot'] },

/* ===== BOTTLES ===== */
{ id:'fmax', cat:'bottle', group:'Standgerät', brand:'Ebac', name:'F-Max', serie:'', img:'b_fmax', configs:[['F-Max CC, kalt',370],['F-Max HC, heiß und kalt',470]],
  sub:'Bottle-Spender, mobil auf Rollen', price:370,
  water:['raum','kalt'], num:null, metric:'5 bis 10 °C',
  features:['Flexibel einsetzbar durch Rollen hinten am Gerät','Raumtemperiertes, gekühltes oder optional heißes Wasser','Integrierter Becherhalter','Hoher Wasserauslass, auch für große Gefäße','Austauschbare Seitenblenden zur optischen Anpassung','Keine feste Wasserleitung, Steckdose reicht'],
  specs:[['Maße mit Flasche','39 × 145 × 39 cm'],['Kaltes Wasser','5 bis 10 °C'],['Wasserarten','raumtemperiert, gekühlt, optional heiß'],['Becherspender','integriert'],['Mobil','Rollen hinten am Gerät'],['Zapftasten und Auslass','getrennt, für höhere Hygiene'],['Seitenblenden','austauschbar, verschiedene Farben']],
  fits:'Standorte ohne Wasseranschluss: Hallen, Baustellen, Messen, Mietflächen.',
  pitch:'Kein Installateur nötig. Bottles liefern wir planbar mit.',
  related:['aqua'] },
{ id:'aqua', cat:'bottle', group:'Standgerät', brand:'Cosmetal', name:'Aquality CO₂', serie:'', img:'b_aqua', configs:[['Aquality C',1399]],
  sub:'Bottle-Spender mit Sprudel', price:1399,
  water:['still','kalt','sprudel'], num:null, metric:'3 bis 10 °C',
  features:['Kompakt und platzsparend, passt in jeden Bürobereich','Gekühltes stilles und sprudelndes Wasser auf Knopfdruck','Integrierter Becherspender','Optional mit UV-C-Hygienebestrahlung am Auslass','CO₂-Flasche unsichtbar im Gehäuse, bei Bedarf extern','Optional Waterstopp: schaltet bei leerer Flasche ab'],
  specs:[['Maße B × H × T','33,7 × 112 × 34 cm (ohne Flasche)'],['Gewicht','24 kg ohne Flasche'],['Wasserarten','still, gekühlt, sprudelnd'],['Kältebereich','3 bis 10 °C bei 10 bis 30 °C Raumtemperatur'],['Zapfleistung','max. ca. 3 l/h gekühlt'],['Becherspender','integriert'],['CO₂-Flasche','2 kg empfohlen, reicht für ca. 500 l']],
  fits:'Büros ohne Wasseranschluss, die trotzdem Sprudel wollen.',
  pitch:'Sprudel ohne Festwasseranschluss.',
  related:['fmax'] },

/* ===== KAFFEEVOLLAUTOMATEN ===== */
{ id:'magic', cat:'kaffee', group:'Tischgerät', brand:'Saeco', name:'Magic', serie:'', img:'k_magic', configs:[['Magic B2',1889],['Magic B2+',2184],['Magic M2',2227],['Magic M2+',2520]],
  sub:'Kaffee neu gedacht, mit Leistung und Design', price:1889, num:80, metric:'80 Tassen/Tag', water:[],
  features:['Kompaktes Kraftpaket: passt in jede Nische, bis zu 80 Tassen täglich','Betrieb über 4-Liter-Tank oder Festwasseranschluss','Bohnen und Pulver von oben einfüllen, ohne die Tür zu öffnen','Mikrometrische Mahlgradeinstellung','Satzbehälter und Tropfschale spülmaschinengeeignet'],
  specs:[['Maße','305 × 635 × 430 mm'],['Gewicht','14,8 bis 15,3 kg'],['Leistung','1.900 W, 230 V, 50 Hz'],['Tagesleistung','80 Tassen'],['Wasser','4-l-Tank oder Festwasser'],['Bohnenbehälter','1,2 kg'],['Mahlwerk','Stahl-Kegelmahlwerk, 8 Stufen']],
  fits:'Kleine Büros, Praxen und Kanzleien.',
  pitch:'Tank oder Festwasser, deshalb überall einsetzbar.',
  accessories:['Milchkühler 1 l','Mini-Gehäuse für Chip- oder Kreditkartensystem','Seitliches Bezahlmodul'],
  related:['vitro','g100k'] },
{ id:'vitro', cat:'kaffee', group:'Tischgerät', brand:'Azkoyen', name:'Vitro S1 EVO', serie:'', img:'k_vitro', configs:[['Vitro S1 EVO V20, Tank',2780],['Vitro S1 EVO V20, Festwasser',2816],['Vitro S1 Classic V20, Tank',2625],['Vitro S1 Classic V20, Festwasser',2635]],
  sub:'Kompakt, bis 80 Tassen', price:2780, num:80, metric:'80 Tassen/Tag', water:[],
  features:['Kompakt, passt in jede Nische','Betrieb über 4-Liter-Tank oder Festwasseranschluss','Bohnen und Pulver von oben einfüllen','Satzbehälter und Tropfschale spülmaschinengeeignet'],
  specs:[['Maße','305 × 635 × 430 mm'],['Leistung','1.900 W, 230 V, 50 Hz'],['Tagesleistung','80 Tassen'],['Wasser','4-l-Tank oder Festwasser'],['Bohnenbehälter','1,2 kg']],
  fits:'Kleine Büros und Besprechungsräume.',
  internal:'Datenblatt prüfen: Texte und technische Werte in der Canva-Präsentation sind 1:1 vom Saeco Magic übernommen.',
  accessories:['Milchkühler 1 l','Mini-Gehäuse für Chip- oder Kreditkartensystem','Seitliches Bezahlmodul'],
  related:['magic','g100k'] },
{ id:'g100k', cat:'kaffee', group:'Tischgerät', brand:'Gaggia', name:'G100', serie:'', img:'k_g100', configs:[['G100 ES 2R',4020],['G100 ES 3R',4510],['G100 ES 2RM',5450],['G100 ES 3RM',5940],['G100 2ES 3RM',6180]],
  sub:'Kompakt. Intuitiv. Barista-Qualität.', price:4020, num:100, metric:'100 Tassen/Tag', water:[],
  features:['Kompakte Stellfläche, nur 31 cm breit','7-Zoll-Touchscreen, individuell anpassbar','Brühgruppe Z4000 (7 bis 14 g)','Energieeffizienzklasse A','Höhenverstellbarer Auslauf bis 160 mm','Einfache Brühgruppenentnahme, automatische Reinigung'],
  specs:[['Maße','308 × 570 × 629 mm'],['Gewicht','ca. 35 kg'],['Leistung','1.900 W, 230 bis 240 V'],['Bohnenbehälter','0,6 oder 1,1 kg'],['Instantbehälter','0,9 bis 1,4 kg'],['Auslauf','bis 160 mm höhenverstellbar'],['Tagesleistung','bis 100 Tassen']],
  fits:'Büros mit 20 bis 50 Personen.',
  pitch:'Nur 31 cm breit, Touchscreen wie ein Smartphone.',
  accessories:['Milchkühler','Unterschrank','Bezahlsysteme'],
  related:['g300','magic'] },
{ id:'g300', cat:'kaffee', group:'Tischgerät', brand:'Gaggia', name:'G300', serie:'', img:'k_g300', configs:[['G300 Krea ES4R',5840]],
  sub:'Leistungsstark und platzsparend', price:5840, num:150, metric:'150 Tassen/Tag', water:[],
  features:['Bis zu 150 Tassen am Tag','10-Zoll-Touchscreen mit bis zu 12 Tasten pro Seite','Intelligenter 3-Tassen-Sensor erkennt die Tassengröße','800-cc-Boiler für 30 % mehr Leistung in Spitzenzeiten','Pulvermilch spart bis zu 40 % Betriebskosten gegenüber Frischmilch','Brühgruppe Z4000'],
  specs:[['Maße','410 × 582 × 770 mm (831 mm mit 2,2-kg-Behälter)'],['Gewicht','42 kg'],['Leistung','1.900 W, 230 bis 240 V'],['Tagesleistung','150 Tassen'],['Bohnenbehälter','1,2 kg oder 2,2 kg'],['Instantbehälter','3']],
  fits:'Bäckereien, Büros, Hotels und Minimärkte.',
  pitch:'Pulvermilch senkt die Betriebskosten um bis zu 40 %.',
  accessories:['Unterschrank','Bezahlsysteme','Tassenwärmer'],
  related:['g100k','g500'] },
{ id:'g500', cat:'kaffee', group:'Tischgerät', brand:'Gaggia', name:'G500', serie:'', img:'k_g500', configs:[['G500 Kalea ES3R7M',11020],['G500 Kalea 2ES3R7M',11440]],
  sub:'Maximale Vielfalt. Volle Kontrolle.', price:11020, num:200, metric:'200 Tassen/Tag', water:[],
  features:['Bis zu 200 Tassen am Tag','7-Zoll-Touchscreen mit Self-Service-Modus','On-Board-Milchsystem mit automatischer Dampfreinigung','Brühgruppe Z4000 iX mit beheizter Edelstahlkammer','PureZone antibakterielle Folie und Coffee APPeal für kontaktlose Bedienung'],
  specs:[['Maße','368 × 583 × 788 mm'],['Gewicht','47 kg'],['Bohnenbehälter','1,2 kg'],['Instantbehälter','1,5 l'],['Brüher','Z4000 iX (14 oder 21 g)'],['Boiler','2 × 0,8 l (Heißwasser und Dampf)'],['Auslaufhöhe','72 bis 167 mm']],
  fits:'Gastronomie, Retail, Bäckerei und Hotel.',
  pitch:'Milchsystem reinigt sich selbst, ohne Demontage.',
  accessories:['Milchkühler','Unterschrank','Bezahlsysteme'],
  related:['g300','g700'] },
{ id:'g700', cat:'kaffee', group:'Tischgerät', brand:'Gaggia', name:'G700', serie:'', img:'k_g700', configs:[['G700 2ES3RM',14220],['G700 2ES3RM Dual Milk',14990]],
  sub:'High Volume. High Performance. High Class.', price:14220, num:300, metric:'300 Tassen/Tag', water:[],
  features:['Bis zu 300 Tassen am Tag','EvoMilk-System für heißen und kalten Milchschaum','DualMilk: zwei Milchsorten gleichzeitig','10-Zoll-Touchscreen, individualisierbar','Brühgruppe Z4000 iX (14 bis 21 g)','Energieeffizienzklasse A'],
  specs:[['Maße','368 × 586 × 783 mm'],['Gewicht','ca. 45 kg'],['Bohnenbehälter','1,2 kg'],['Instantbehälter','1,5 l'],['Brüher','Z4000 iX, Edelstahl, vorgeheizt'],['Touchscreen','10 Zoll'],['Milchsystem','EvoMilk + automatische Reinigung']],
  fits:'Große Büros, Hotels, Kantinen mit hohem Milchanteil.',
  pitch:'Zwei Milchsorten gleichzeitig, zum Beispiel Kuh- und Hafermilch.',
  accessories:['Milchkühler','Unterschrank','Bezahlsysteme'],
  related:['g500','masterbrew'] },
{ id:'masterbrew', cat:'kaffee', group:'Tischgerät', brand:'Gaggia', name:'MasterBrew GS', serie:'', img:'k_mb', configs:[['GS MasterBrew B2C',7494],['GS MasterBrew 2B2C',7760]],
  sub:'Smart. Elegant. Nachhaltig.', price:7494, num:250, metric:'250 Tassen/Tag', water:[],
  features:['Für bis zu 250 Tassen am Tag, große Büros und Selbstbedienung','12-Zoll-Glas-Touchscreen mit App-Steuerung','Zwei Bohnen- und bis zu vier Instantbehälter','Optional mit stillem und sprudelndem Wasser','Energieklasse A++ dank Ecomode und isoliertem Boiler','18 % schnellere Reinigung, 20 % weniger Wartungsaufwand'],
  specs:[['Maße','450 × 525 × 870 mm'],['Gewicht','62 kg'],['Brühgruppe','Z4000'],['Bohnenbehälter','2 × 2 kg'],['Instantbehälter','3 × 2,7 l'],['Touchscreen','12 Zoll Glas, kapazitiv'],['Konnektivität','USB, LAN, WLAN, Bluetooth, Cloud']],
  fits:'Große Büros und Self-Service-Bereiche.',
  pitch:'Kaffee und Tafelwasser still und sprudelnd aus einem Gerät möglich.',
  accessories:['Holzunterschrank Einzeltür 70 × 60 × 85 cm','Holzunterschrank Doppeltür 100 × 60 × 85 cm','Unterschrank mit Abfallbehälter 41 × 57 × 85 cm','Kit Wasserselbstversorgung 20 l Tank + Flow Jet','Kit Abwasserfestanschluss','Kit Satzabwurf','Seitlicher Tank 5 l','Bezahlsysteme'],
  related:['g700'] },
{ id:'barista200', cat:'kaffee', group:'Standautomat', brand:'Evoca', name:'Barista 200', serie:'', img:'k_b200', configs:[['Barista 200 ES 5',3300]],
  sub:'Becherautomat für kleine bis mittlere Standorte', price:3300, num:200, metric:'bis 200 Tassen/Tag', water:[],
  features:['Für kleine bis mittlere Standorte','10 Direktwahltasten und LED-beleuchteter Ausgabebereich','Freemix-System für cremigere Instantgetränke','Brühgruppe Z4000 L','Wartungsfreundlich: farbcodierte Teile'],
  specs:[['Maße','750 × 410 × 564 mm'],['Gewicht','42 kg'],['Bechermagazin','200 Becher (Ø 70 bis 71 mm)'],['Bohnenbehälter','1,2 kg'],['Milchpulver','1,9 kg'],['Schokolade','1,9 kg'],['Tee','1 l']],
  fits:'Pausenräume, Werkstätten, Wartebereiche mit Becherausgabe.',
  internal:'Tagesleistung prüfen: Präsentation nennt oben 200, in den technischen Details 100 Tassen.',
  accessories:['Unterschrank','Mini-Gehäuse','Seitliches Bezahlmodul','Münzprüfer, Münzwechsler, Karten- oder Chipsystem','Kit Wasserselbstversorgung 20 l Tank + Flow Jet','Kit Abwasserfestanschluss'],
  related:['barista500pro'] },
{ id:'barista500pro', cat:'kaffee', group:'Standautomat', brand:'Evoca', name:'Barista 500 Pro Touch', serie:'', img:'k_b500pro', configs:[['Barista 500 Pro Touch ES 7',8625]],
  sub:'Becherautomat für große Standorte', price:8625, num:300, metric:'über 200 Tassen/Tag', water:[],
  features:['Für große Standorte mit mehr als 200 Tassen am Tag','Touch-Bedienung, LED-beleuchteter Ausgabebereich','Freemix-System für cremigere Instantgetränke','Brühgruppe Z4000 L','Wartungsfreundlich: farbcodierte Teile'],
  specs:[['Maße','750 × 410 × 564 mm'],['Gewicht','42 kg'],['Bechermagazin','500 Becher (Ø 70 bis 71 mm)'],['Bohnenbehälter','3,2 kg'],['Milchpulver','6 l'],['Schokolade, Zucker, Suppe','je 4,5 l'],['Tee','2,5 l']],
  fits:'Produktion, Kantine, Schichtbetrieb.',
  internal:'Maße in der Präsentation identisch mit Barista 200, bitte gegen Datenblatt prüfen.',
  accessories:['Unterschrank','Mini-Gehäuse','Seitliches Bezahlmodul','Münzprüfer, Münzwechsler, Karten- oder Chipsystem','Kit Wasserselbstversorgung 20 l Tank + Flow Jet','Kit Abwasserfestanschluss'],
  related:['barista500ob','barista200'] },
{ id:'barista500ob', cat:'kaffee', group:'Standautomat', brand:'Evoca', name:'Barista 500 One Black Touch', serie:'', img:'k_b500ob', configs:[['Barista 500 One Black Touch ES',5700]],
  sub:'Becherautomat in Schwarz für große Standorte', price:5700, num:300, metric:'über 200 Tassen/Tag', water:[],
  features:['Für große Standorte mit mehr als 200 Tassen am Tag','Touch-Bedienung, LED-beleuchteter Ausgabebereich','Freemix-System für cremigere Instantgetränke','Brühgruppe Z4000 L'],
  specs:[['Maße','750 × 410 × 564 mm'],['Gewicht','42 kg'],['Bechermagazin','500 Becher (Ø 70 bis 71 mm)'],['Bohnenbehälter','3,2 kg'],['Milchpulver','6 l'],['Schokolade, Zucker, Suppe','je 4,5 l'],['Tee','2,5 l']],
  fits:'Große Standorte mit Anspruch an die Optik.',
  internal:'Unterschied zum Pro Touch in der Präsentation nicht beschrieben.',
  accessories:['Unterschrank','Mini-Gehäuse','Seitliches Bezahlmodul','Münzprüfer, Münzwechsler, Karten- oder Chipsystem'],
  related:['barista500pro'] },

/* ===== SIEBTRÄGER & MÜHLEN (Gaggia Milano) ===== */
{ id:'gt3-1', cat:'barista', group:'Siebträger', line:'GT3', brand:'Gaggia', name:'GT3 1-gruppig', serie:'', img:'gg_gt3_1', badge:'Neu',
  sub:'Kompakter Einstieg', price:3050, code:'GT3091NW', num:1, metric:'1 Gruppe', water:[],
  features:['Drehbare Edelstahl-Dampflanze','Seitlicher Heißwasserauslass','1,54-Zoll-Farb-LCD, Programmierung auf Knopfdruck','4 programmierbare Tasten und eine Dauerlauf-Taste','Autosteam optional','Tall Cup optional'],
  specs:[['Maße B × H × T','450 × 520 × 420 mm'],['Stromversorgung','230 V / 50 bis 60 Hz'],['Leistungsaufnahme','2.500 W'],['Boiler','5 l'],['Autosteam','optional'],['Heißwasserauslass','1'],['Gewicht','35 kg'],['Farbe','schwarz']],
  fits:'Kleine Cafés, Büros mit Barista-Anspruch, Hotelbar.',
  related:['gt3-2k','g4'] },
{ id:'gt3-2k', cat:'barista', group:'Siebträger', line:'GT3', brand:'Gaggia', name:'GT3 2-gruppig Kompakt', serie:'', img:'gg_gt3_2k', badge:'Neu',
  sub:'Zwei Gruppen, kleiner Boiler', price:3809, code:'GT3C092NW', num:2, metric:'2 Gruppen', water:[],
  features:['Drehbare Edelstahl-Dampflanze','Seitlicher Heißwasserauslass','1,54-Zoll-Farb-LCD, Programmierung auf Knopfdruck','4 programmierbare Tasten und eine Dauerlauf-Taste','Autosteam optional','Tall Cup optional'],
  specs:[['Maße B × H × T','710 × 520 × 420 mm'],['Stromversorgung','230 V / 50 bis 60 Hz'],['Leistungsaufnahme','3.000 W'],['Boiler','8 l'],['Autosteam','optional'],['Heißwasserauslass','1'],['Gewicht','50 kg'],['Farbe','schwarz']],
  fits:'Cafés und Bäckereien mit mittlerer Frequenz.',
  related:['gt3-2','gt3-1'] },
{ id:'gt3-2', cat:'barista', group:'Siebträger', line:'GT3', brand:'Gaggia', name:'GT3 2-gruppig Pot', serie:'', img:'gg_gt3_2', gallery:['gg_gt3_life'],
  sub:'Zwei Gruppen, 11-Liter-Boiler', price:3974, code:'GT3092NPW', num:2, metric:'2 Gruppen', water:[],
  features:['Drehbare Edelstahl-Dampflanze','Seitlicher Heißwasserauslass','1,54-Zoll-Farb-LCD, Programmierung auf Knopfdruck','4 programmierbare Tasten und eine Dauerlauf-Taste'],
  specs:[['Maße B × H × T','710 × 520 × 420 mm'],['Stromversorgung','230 V / 50 bis 60 Hz'],['Leistungsaufnahme','3.500 W'],['Boiler','11 l'],['Autosteam','optional'],['Heißwasserauslass','1'],['Gewicht','54 kg'],['Farbe','schwarz']],
  fits:'Cafés, Bäckereien und Hotels.',
  related:['gt3-2t','gt3-2k','g6'] },
{ id:'gt3-2t', cat:'barista', group:'Siebträger', line:'GT3', brand:'Gaggia', name:'GT3 2-gruppig Tall', serie:'', img:'gg_gt3_2t',
  sub:'Tall Cup für To-go-Becher', price:4124, code:'GT3092NTW', num:2, metric:'2 Gruppen', water:[],
  features:['Drehbare Edelstahl-Dampflanze','Seitlicher Heißwasserauslass','1,54-Zoll-Farb-LCD, Programmierung auf Knopfdruck','4 programmierbare Tasten und eine Dauerlauf-Taste','Vierteldrehventile (Dampfhahn)','Tall Cup','Autosteam optional'],
  specs:[['Maße B × H × T','710 × 520 × 420 mm'],['Stromversorgung','230 V / 50 bis 60 Hz'],['Leistungsaufnahme','2.600 W'],['Boiler','11 l'],['Autosteam','optional'],['Heißwasserauslass','1'],['Gewicht','54 kg'],['Farbe','schwarz']],
  fits:'Bäckereien und Coffee-to-go.',
  related:['gt3-2','gt7-2t'] },
{ id:'gt7-2', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 2-gruppig Pot Mix', serie:'', img:'gg_gt7_2', gallery:['gg_gt7_life'],
  sub:'Premium mit RGB-Tasten', price:5870, code:'GT7092NPWIXM schwarz · GT7092HPWIXM weiß', num:2, metric:'2 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Mix water (Kaltwasser-Beimischung)','Tassenwärmer','Powersteam HT optional','Tall Cup optional'],
  specs:[['Maße B × H × T','770 × 540 × 570 mm'],['Stromversorgung','220 bis 240 V'],['Leistungsaufnahme','4.200 W'],['Boiler','13 l'],['Autosteam','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','63 kg'],['Farben','weiß, schwarz']],
  fits:'Gastronomie und Hotels mit Anspruch an Design.',
  related:['gt7-2t','gt7-2ps','g10'] },
{ id:'gt7-2t', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 2-gruppig Tall Pot Mix', serie:'', img:'gg_gt7_2t',
  sub:'Premium mit Tall Cup', price:6320, code:'GT7092NTPWXM schwarz · GT7092HTPWXM weiß', num:2, metric:'2 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Mix water (Kaltwasser-Beimischung)','Tassenwärmer','Tall Cup','Powersteam HT optional'],
  specs:[['Maße B × H × T','770 × 540 × 570 mm'],['Stromversorgung','220 bis 240 V'],['Leistungsaufnahme','4.200 W'],['Boiler','13 l'],['Autosteam','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','63 kg'],['Farben','weiß, schwarz']],
  fits:'Coffee-to-go und Bäckereien mit Premium-Anspruch.',
  related:['gt7-2','gt7-2tps'] },
{ id:'gt7-2ps', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 2-gruppig Pot Mix PS', serie:'', img:'gg_gt7_2ps',
  sub:'Mit Power Steam', price:7470, code:'GT7092NPWIS3XM schwarz · GT7092HPWIS3XM weiß', num:2, metric:'2 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Tassenwärmer','Power Steam','Water mix','Powersteam HT optional','Tall Cup optional'],
  specs:[['Maße B × H × T','770 × 540 × 570 mm'],['Stromversorgung','220 bis 240 V'],['Leistungsaufnahme','4.200 W'],['Boiler','13 l'],['Autosteam','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','63 kg'],['Farben','weiß, schwarz']],
  fits:'Betriebe mit hohem Milchgetränke-Anteil.',
  related:['gt7-2','gt7-2tps'] },
{ id:'gt7-2tps', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 2-gruppig Tall Pot Mix PS', serie:'', img:'gg_gt7_2tps',
  sub:'Power Steam und Tall Cup', price:8220, code:'GT7092NTPWS3XM schwarz · GT7092HTPWS3XM weiß', num:2, metric:'2 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Tall Cup','Power Steam','Mix water (Kaltwasser-Beimischung)','Powersteam HT optional'],
  specs:[['Maße B × H × T','770 × 540 × 570 mm'],['Stromversorgung','220 bis 240 V'],['Leistungsaufnahme','4.200 W'],['Boiler','13 l'],['Dampflanze','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','63 kg'],['Farben','weiß, schwarz']],
  fits:'Spitzengerät für Coffee-to-go mit viel Milchschaum.',
  related:['gt7-2ps','gt7-2t'] },
{ id:'gt7-3', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 3-gruppig Pot Mix', serie:'', img:'gg_gt7_3', gallery:['gg_gt7_life'],
  sub:'Drei Gruppen für hohe Frequenz', price:6620, code:'GT7093NPWIXM schwarz · GT7093HTPWXM weiß', num:3, metric:'3 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Mix water (Kaltwasser-Beimischung)','Tassenwärmer','Powersteam HT optional','Tall Cup optional'],
  specs:[['Maße B × H × T','940 × 540 × 570 mm'],['Stromversorgung','380 V'],['Leistungsaufnahme','5.500 W'],['Boiler','18 l'],['Autosteam','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','76 kg'],['Farben','weiß, schwarz']],
  fits:'Große Cafés, Hotels, Events.',
  internal:'380-V-Anschluss prüfen.',
  related:['gt7-3t','gt7-2'] },
{ id:'gt7-3t', cat:'barista', group:'Siebträger', line:'GT7', brand:'Gaggia', name:'GT7 3-gruppig Tall Pot Mix', serie:'', img:'gg_gt7_3t',
  sub:'Drei Gruppen mit Tall Cup', price:7070, code:'GT7093NTPWXM', num:3, metric:'3 Gruppen', water:[],
  features:['Keypad und 2,8-Zoll-TFT-Display','Cool Touch Dampflanze','Tasten mit RGB-LED','Seitlicher Heißwasserauslass','Tall Cup','Mix water (Kaltwasser-Beimischung)','Powersteam HT optional'],
  specs:[['Maße B × H × T','940 × 540 × 570 mm'],['Stromversorgung','220 bis 240 V'],['Leistungsaufnahme','5.500 W'],['Boiler','18 l'],['Autosteam','Cool Touch'],['Heißwasserauslass','1'],['Gewicht','76 kg'],['Farben','weiß, schwarz']],
  fits:'Coffee-to-go mit hoher Frequenz.',
  internal:'Gaggia-Katalog nennt 770 mm Breite (vermutlich Druckfehler, 3-gruppig = 940 mm). Stromversorgung vor Angebot prüfen.',
  related:['gt7-3','gt7-2t'] },
{ id:'nera2', cat:'barista', group:'Siebträger', line:'La Nera', brand:'Gaggia', name:'La Nera 2-gruppig', serie:'', img:'gg_nera2', gallery:['gg_nera_life'],
  sub:'Klassiker für den Einstieg', price:3890, code:'MGR092N', num:2, metric:'2 Gruppen', water:[],
  features:['4 programmierbare Dosierstufen und 1 stufenloser Regler je Brühgruppe','Ergonomische Hähne für Heißwasser und Dampfdüse','Manometer','LED-beleuchteter Ausgabebereich'],
  specs:[['Maße B × T × H','730 × 530 × 420 mm'],['Gewicht','52 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','2.800 W'],['Dampfboiler','13 l / 2.800 W'],['Dampflanzen','2'],['Heißwasserauslass','1'],['Manometer','ja'],['Tassenwärmer','nein'],['Bedienfeld','5 hinterleuchtete Tasten je Gruppe'],['Farbe','silber / schwarz']],
  fits:'Cafés und Bäckereien, günstigster Zweigruppen-Siebträger.',
  pitch:'Günstigster 2-Gruppen-Siebträger im Programm.',
  related:['lv2','gt3-2'] },
{ id:'lv2', cat:'barista', group:'Siebträger', line:'La Vetro', brand:'Gaggia', name:'La Vetro 2-gruppig', serie:'', img:'gg_lv2',
  sub:'Kupferkessel, PID-geregelt', price:4464, code:'MGV0925HPI weiß · MGV0925NPI schwarz', num:2, metric:'2 Gruppen', water:[],
  features:['4 programmierbare Dosierstufen und 1 stufenloser Regler je Gruppe','Vierteldrehungs-Systeme','Kupferkessel mit Thermosiphon und Wärmetauscher je Gruppe','PID-Temperaturregelung','Eco-Modus'],
  specs:[['Maße B × T × H','760 × 530 × 470 mm'],['Gewicht','55 kg'],['Spannung','230 V / 50 Hz'],['Stromaufnahme','3.700 W'],['Dampfboiler','13 l / 3.500 W'],['Temperaturregelung','PID'],['Dampflanzen','2, Vierteldrehung'],['Manometer','ja'],['Tassenwärmer','ja'],['Bedienfeld','5 hinterleuchtete Tasten'],['Farben','weiß, schwarz']],
  fits:'Cafés und Restaurants mit Anspruch an Temperaturstabilität.',
  related:['lv3','lvp2','nera2'] },
{ id:'lv3', cat:'barista', group:'Siebträger', line:'La Vetro', brand:'Gaggia', name:'La Vetro 3-gruppig', serie:'', img:'gg_lv3',
  sub:'Drei Gruppen, Kupferkessel', price:5248, code:'MGV0935HPI weiß · MGV0935NPI schwarz', num:3, metric:'3 Gruppen', water:[],
  features:['4 programmierbare Dosierstufen und 1 stufenloser Regler je Gruppe','Vierteldrehungs-Systeme','Kupferkessel mit Thermosiphon je Gruppe','PID-Temperaturregelung','Eco-Modus'],
  specs:[['Maße B × T × H','930 × 530 × 470 mm'],['Gewicht','66 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','4.800 W'],['Dampfboiler','18 l / 4.600 W'],['Temperaturregelung','PID'],['Dampflanzen','2, Vierteldrehung'],['Manometer','ja'],['Tassenwärmer','ja'],['Farben','weiß, schwarz']],
  fits:'Hohe Frequenz, günstigster 3-Gruppen-Siebträger.',
  related:['lv2','lvp3'] },
{ id:'lvp2', cat:'barista', group:'Siebträger', line:'La Vetro Pro', brand:'Gaggia', name:'La Vetro Pro 2-gruppig', serie:'', img:'gg_lvp2',
  sub:'TFT-Display und Autosteam', price:6000, code:'MGV0926HPWS2M weiß · MGV0926NPWS2M schwarz', num:2, metric:'2 Gruppen', water:[],
  features:['2,8-Zoll-TFT-Display','4 programmierbare Dosierstufen und 1 stufenloser Regler je Brühgruppe','2 Dampfdüsen (1 klassisch + 1 Autosteam)','Isolierter Kupferkessel','LED-beleuchtete Seitenwände'],
  specs:[['Maße B × T × H','760 × 530 × 470 mm'],['Gewicht','55 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','3.700 W'],['Dampfboiler','13 l / 3.500 W, isoliert, Kupfer'],['Temperaturregelung','PID'],['Manometer','ja'],['Tassenwärmer','nein'],['Eco-Modus','ja'],['Farben','weiß, schwarz']],
  fits:'Gastronomie, die Milchschaum automatisieren will.',
  related:['lvp2t','lvp3','lv2'] },
{ id:'lvp3', cat:'barista', group:'Siebträger', line:'La Vetro Pro', brand:'Gaggia', name:'La Vetro Pro 3-gruppig', serie:'', img:'gg_lvp3',
  sub:'Drei Gruppen, TFT und Autosteam', price:6950, code:'MGV0936HPWS2M weiß · MGV0936NPWS2M schwarz', num:3, metric:'3 Gruppen', water:[],
  features:['2,8-Zoll-TFT-Display','4 programmierbare Dosierstufen und 1 stufenloser Regler je Brühgruppe','2 Dampfdüsen (1 klassisch + 1 Autosteam)','Isolierter Kupferkessel','LED-beleuchtete Seitenwände'],
  specs:[['Maße B × T × H','930 × 530 × 470 mm'],['Gewicht','66 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','4.800 W'],['Dampfboiler','18 l / 4.600 W, isoliert, Kupfer'],['Temperaturregelung','PID'],['Manometer','ja'],['Eco-Modus','ja'],['Farben','weiß, schwarz']],
  fits:'Große Betriebe mit hoher Frequenz.',
  related:['lvp3t','lvp2','lv3'] },
{ id:'lvp2t', cat:'barista', group:'Siebträger', line:'La Vetro Pro', brand:'Gaggia', name:'La Vetro Pro 2-gruppig Tall Cup', serie:'', img:'gg_lvpt2',
  sub:'Pro mit Tall Cup Brühgruppen', price:5950, code:'MGV0926HTPWS2M weiß · MGV0926NTPWS2M schwarz', num:2, metric:'2 Gruppen', water:[],
  features:['2,8-Zoll-TFT-Display','4 programmierbare Dosierstufen und 1 stufenloser Regler je Brühgruppe','2 Dampfdüsen (1 klassisch + 1 Autosteam)','Isolierter Kupferkessel','2 Tall Cup Brühgruppen'],
  specs:[['Maße B × T × H','760 × 530 × 530 mm'],['Gewicht','55 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','3.700 W'],['Dampfboiler','13 l / 3.500 W, isoliert, Kupfer'],['Temperaturregelung','PID'],['Heißwassermischer','nein'],['Manometer','ja'],['Eco-Modus','ja'],['Farben','weiß, schwarz']],
  fits:'Coffee-to-go mit Autosteam.',
  internal:'Laut Gaggia-Liste 50 € günstiger als die Pro ohne Tall Cup.',
  related:['lvp2','lvp3t'] },
{ id:'lvp3t', cat:'barista', group:'Siebträger', line:'La Vetro Pro', brand:'Gaggia', name:'La Vetro Pro 3-gruppig Tall Cup', serie:'', img:'gg_lvpt3',
  sub:'Drei Tall Cup Brühgruppen', price:7150, code:'MGV0936HTPWS2M weiß · MGV0936NTPWS2M schwarz', num:3, metric:'3 Gruppen', water:[],
  features:['2,8-Zoll-TFT-Display','4 programmierbare Dosierstufen und 1 stufenloser Regler je Brühgruppe','2 Dampfdüsen (1 klassisch + 1 Autosteam)','Isolierter Kupferkessel','3 Brühgruppen Tall Cup','Heißwassermischer'],
  specs:[['Maße B × T × H','930 × 530 × 530 mm'],['Gewicht','66 kg'],['Stromversorgung','230 V / 50 Hz'],['Leistungsaufnahme','4.800 W'],['Dampfboiler','18 l / 4.600 W, isoliert, Kupfer'],['Temperaturregelung','PID'],['Heißwassermischer','ja'],['Manometer','ja'],['Eco-Modus','ja'],['Farben','weiß, schwarz']],
  fits:'Große Coffee-to-go-Standorte.',
  related:['lvp3','gt7-3t'] },
{ id:'g4', cat:'barista', group:'Mühle', line:'Mühle', brand:'Gaggia', name:'Kaffeemühle G4', serie:'', img:'gg_g4', badge:'Neu',
  sub:'64 mm Flachmahlscheiben', price:1100, code:'PGW002H weiß · PGW002N schwarz', num:2, metric:'2 g/s', water:[],
  features:['64 mm flache Mahlscheiben aus Edelstahl','Schnellstartfunktion','Voreinstellungen','Kapazitives Display'],
  specs:[['Maße L × B × H','177 × 390 × 580 mm'],['Gewicht','12,5 kg'],['Stromversorgung','220 V / 50 Hz'],['Leistungsaufnahme','380 bis 415 W'],['Trichter','1,2 kg'],['Mahlscheiben','64 mm'],['Bedienung','kapazitives Display'],['Leistung','2 g/s'],['Farben','weiß, schwarz']],
  fits:'1- und 2-gruppige Siebträger mit normaler Frequenz.',
  accessories:['Tamper Ø 57 mm, exklusiv für G4/G6 (NT1042, 17 €)'],
  related:['g6','qpress','gt3-1'] },
{ id:'g6', cat:'barista', group:'Mühle', line:'Mühle', brand:'Gaggia', name:'Kaffeemühle G6', serie:'', img:'gg_g6', badge:'Neu',
  sub:'75 mm Flachmahlscheiben, 4 g/s', price:1380, code:'PGW001H weiß · PGW001N schwarz', num:4, metric:'4 g/s', water:[],
  features:['75 mm Flachmahlscheiben aus Edelstahl','Schnellstartfunktion','Voreingestellte Programme','Integrierter Lüfter'],
  specs:[['Maße L × B × H','177 × 390 × 650 mm'],['Gewicht','15,5 kg'],['Stromversorgung','220 V / 50 Hz'],['Leistungsaufnahme','550 bis 650 W'],['Trichter','1,2 kg'],['Mahlscheiben','75 mm'],['Bedienung','kapazitives Display'],['Leistung','4 g/s'],['Farben','weiß, schwarz']],
  fits:'Hohe Frequenz, 2- und 3-gruppige Siebträger.',
  accessories:['Tamper Ø 57 mm, exklusiv für G4/G6 (NT1042, 17 €)'],
  related:['g4','g10','qpress'] },
{ id:'g10', cat:'barista', group:'Mühle', line:'Mühle', brand:'Gaggia', name:'Kaffeemühle G10 EVO eLink', serie:'', img:'gg_g10',
  sub:'Mit App und Bluetooth', price:2266, code:'PGC051H weiß · PGC051N schwarz · PGC051A kupfer', num:3, metric:'2 bis 3 g/s', water:[],
  features:['Flache Mahlscheiben aus Edelstahl','Schnellstartfunktion','Voreingestellte Programme','eLink: kostenlose App, Leistung und Wartung per Bluetooth überwachen','4,3-Zoll-Touchscreen'],
  specs:[['Maße L × B × H','190 × 370 × 628 mm'],['Gewicht','16 kg'],['Stromversorgung','220 V / 50 Hz'],['Leistungsaufnahme','525 W'],['Trichter','1,2 kg'],['Mahlscheiben','64 mm (laut Datenblatt)'],['Bedienung','4,3-Zoll-Touchscreen'],['Betriebsart','vormahlen, instant, manuell'],['Leistung','2 bis 3 g/s'],['Farben','weiß, schwarz, kupfer']],
  fits:'Premium-Gastronomie, die Mahlmenge und Wartung digital steuern will.',
  internal:'Gaggia-Katalog nennt bei den Merkmalen 75 mm, in der Tabelle 64 mm Mahlscheiben.',
  related:['g6','gt7-2'] },
{ id:'qpress', cat:'barista', group:'Stampfer', line:'Zubehör', brand:'Qpress', name:'Q-Press Stamper', serie:'', img:'gg_qpress',
  sub:'Automatisches Tampen, 10 bis 30 kg', price:993, code:'RQA010H weiß · RQA010N schwarz', num:null, metric:'10 bis 30 kg', water:[],
  features:['Präzises, gleichmäßiges automatisches Tampen mit programmierbarem Druck von 10 bis 30 kg','Schnelle Zubereitung für effizienten Service','Kompatibel mit allen Siebhaltern dank verstellbarer Führung (52 und 58 mm)','Automatischer Reinigungsmodus'],
  specs:[['Maße L × B × H','140 × 260 × 341 mm'],['Gewicht','6 kg'],['Stromversorgung','220 V / 50 Hz'],['Leistungsaufnahme','20 W'],['Druck','10 bis 30 kg, programmierbar'],['Siebträger','52 und 58 mm'],['Bedienung','1,54-Zoll-TFT, kapazitive Tastatur'],['Farben','weiß, schwarz']],
  fits:'Betriebe mit wechselndem Personal: gleiche Espressoqualität bei jedem Bezug.',
  related:['g6','g4'] },

/* ===== WARENAUTOMATEN (SandenVendo) ===== */
{ id:'gsnack', cat:'vending', group:'Snackautomat', brand:'SandenVendo', name:'G-Snack Indoor', serie:'', img:'v_gsnack', configs:[['SM6 Metall-Panel ohne Lift',5800],['SM6 Metall-Panel mit Lift',6500],['SM8 Metall-Panel ohne Lift',6400],['SM8 Metall-Panel mit Lift',6840],['SMX 10 Metall-Panel ohne Lift',6700],['SMX 10 Metall-Panel mit Lift',7440],['SLL 12 Metall-Panel ohne Lift',7840],['ST 6 Touch ohne Lift',6300],['ST 6 Touch mit Lift',6900],['ST 8 Touch ohne Lift',6990],['ST 8 Touch mit Lift',7440],['STX 10 Touch ohne Lift',7200],['STX 10 Touch mit Lift',7940],['Slave SS6 ohne / mit Lift','5.000 / 5.700 €'],['Slave SS8 ohne / mit Lift','5.250 / 5.890 €'],['Slave SSX 10 ohne / mit Lift','5.850 / 6.490 €']],
  sub:'Snackautomat mit Produktlift, 4 Größen', price:5800, num:84, metric:'bis 84 Auswahlen', water:[], tags:['snack','drink','indoor'],
  features:['Schneller Produktlift: auch empfindliche Produkte aus den oberen Etagen','Duo Synchro Spirale mit Doppelmotorantrieb für große Produkte','Modulares System','Energiesparend'],
  specs:[['Höhe','1830 mm (mit Stellfüßen)'],['Innentemperatur','+2 bis +18 °C'],['Steuerung','Executive / MDB'],['Kühleinheit','HCD'],['Leistungsaufnahme','350 W'],['Klimaklasse','ST (+16 bis +38 °C)'],['Energieklasse','C']],
  variants:{ cols:['S2L · Twelve','SMX · Ten','SM8 · Eight','SM6 · Six'], rows:[
    ['Maße H × B × T','1830 × 1290 × 900','1830 × 1125 × 845','1830 × 980 × 845','1830 × 830 × 845'],
    ['Gewicht','410 kg','340 kg','310 kg','275 kg'],['Auswahlen pro Etage','12 (6+6)','10','8','6'],
    ['Etagen','6 / max. 7','6 / max. 7','6 / max. 7','6 / max. 7'],['Auswahlen','max. 84','max. 70','max. 56','max. 42'],
    ['Energie kWh/Jahr (Kat. 2)','837','694','681','629'] ]},
  fits:'Pausenräume, Produktion, Schulen und Kliniken.',
  pitch:'Produktlift: auch Glasflaschen und empfindliche Ware aus der obersten Etage.',
  related:['gdrink','brain','gsnackod'] },
{ id:'gdrink', cat:'vending', group:'Getränkeautomat', brand:'SandenVendo', name:'G-Drink Indoor', serie:'', img:'v_gdrink', configs:[['DM6 Metall-Panel',6710],['DM9 Metall-Panel',7165],['DT6 Touch',7125],['DT 9 Touch',7600],['Slave DS 6',6450],['Slave DS 9',6900]],
  sub:'Getränkeautomat für Dosen, PET und Glas', price:6710, num:63, metric:'bis 504 Dosen', water:[], tags:['drink','indoor'],
  features:['Für PET-Flaschen, Glasflaschen, Dosen und Kartons','Hochleistung und ergonomisches Design','Modulares System','Energiesparend'],
  specs:[['Höhe','1830 mm (mit Nivellierschrauben)'],['Innentemperatur','+2 bis +10 °C'],['Steuerung','Executive / MDB'],['Kühleinheit','HCD'],['Leistungsaufnahme','370 W'],['Elektroanschluss','230/240 V, 50/60 Hz'],['Klimaklasse','N (+16 bis +32 °C)'],['Energieklasse','C'],['Flaschen','Ø 43,5 bis 73 mm, H 88 bis 285 mm']],
  variants:{ cols:['DM9 · G-Drink 9','DM6 · G-Drink 6'], rows:[
    ['Maße H × B × T','1830 × 1215 × 845','1830 × 940 × 845'],['Gewicht','345 kg','295 kg'],['Auswahlen pro Etage','9','6'],
    ['Etagen','5 / max. 7','5 / max. 7'],['Auswahlen','45 / max. 63','30 / max. 42'],['Dosen 0,33 l','504','336'],['PET 0,5 l','360','240'],['Energie kWh/Jahr','817','624'] ]},
  fits:'Kantinen und Pausenräume mit hohem Getränkebedarf.',
  related:['gsnack','narrow','gdrinkod'] },
{ id:'narrow', cat:'vending', group:'Getränkeautomat', line:'B&C Design', brand:'SandenVendo', name:'B&C Design Narrowstack', serie:'', img:'v_narrow', configs:[['Narrowstack 6 (XS-C36)',4240],['Narrowstack 7 (S-C37)',4500],['Narrowstack 8 (M-C48)',4740],['Narrowstack L-C4X',5700]],
  sub:'Schachtautomat für Getränke, 4 Größen', price:4240, num:10, metric:'bis 750 Dosen', water:[], tags:['drink','indoor'],
  features:['Über 40 Jahre bewährte Stapeltechnik','Plug & Play','Kosteneffizient und zuverlässig','Umweltfreundlich'],
  specs:[['Höhe','1830 mm'],['Innentemperatur','+1 bis +25 °C'],['Steuerung','Executive / MDB'],['Kühleinheit','HCD'],['Leistungsaufnahme','320 W'],['Elektroanschluss','220/240 V, 50 Hz'],['Klimaklasse','N (+16 bis +32 °C)'],['Produkte','Ø 52 bis 72 mm, H 80 bis 355 mm']],
  variants:{ cols:['L-C4X · 10','M-C48 · 8','S-C47 · 7','XS-C36 · 6'], rows:[
    ['Maße H × B × T','1830 × 1015 × 955','1830 × 850 × 955','1830 × 750 × 955','1830 × 650 × 800'],['Gewicht','375 kg','340 kg','300 kg','280 kg'],
    ['Schächte','10','8','7','6'],['PET 0,5 l','340','272','237','102'],['Slim-Dose 0,25 l','750','600','525','300'],['Dose 0,33 l','680','544','476','306'],
    ['Energieklasse','B','B','B','C'],['Energie kWh/Jahr','577','550','507','566'] ]},
  fits:'Hoher Durchsatz bei Dosen und PET, wenig Platz.',
  related:['flex','super','gdrink'] },
{ id:'flex', cat:'vending', group:'Getränkeautomat', line:'B&C Design', brand:'SandenVendo', name:'B&C Design Flexstack', serie:'', img:'v_flex', configs:[['Flexstack CFX',5700]],
  sub:'Flexible Module für 0,33 bis 1,5 l', price:5700, num:10, metric:'10 Auswahlen', water:[], tags:['drink','indoor'],
  features:['Standard- und Schmalmodule frei kombinierbar','Auch 1-l- und 1,5-l-PET-Flaschen','Plug & Play','Energieklasse B'],
  specs:[['Maße H × B × T','1830 × 1015 × 955 mm'],['Gewicht','375 kg'],['Auswahlen','10'],['Schächte','5 bis 7'],['Steuerung','Executive / MDB'],['Innentemperatur','+1 bis +25 °C'],['Leistungsaufnahme','320 W'],['Energieklasse','B, 577 kWh/Jahr']],
  variants:{ cols:['Standard-Modul','Schmal-Modul'], rows:[
    ['Dose 0,33 l / PET','87 / 3 (3D)','51 / 3 (3D)'],['Flasche 0,5 l PET','29 / 1 (1D)','17 / 1 (1D)'],['Flasche 1,0 l PET','22 bis 24 / 1 (1D)','nicht möglich'],['Flasche 1,5 l','16 bis 18 / 1 (1D)','nicht möglich'] ]},
  fits:'Standorte mit großen Flaschen: Produktion, Sport, Handwerk.',
  related:['narrow','super'] },
{ id:'super', cat:'vending', group:'Getränkeautomat', line:'B&C Design', brand:'SandenVendo', name:'B&C Design Superstack', serie:'', img:'v_super', configs:[['Superstack C26',4750]],
  sub:'Glasflaschen und Pfandsystem', price:4750, num:6, metric:'180 Glasflaschen', water:[], tags:['drink','indoor'],
  features:['Für Glasflaschen 0,5 l, PET und Dosen','Kompatibel mit Pfandrückgabe-System (DRS)','Entwickelt gemäß EU-Verpackungsrichtlinie','Plug & Play'],
  specs:[['Maße H × B × T','1830 × 1015 × 750 mm'],['Gewicht','390 kg'],['Auswahlen / Schächte','6'],['Steuerung','Executive / MDB'],['Innentemperatur','+1 bis +25 °C'],['Leistungsaufnahme','320 W'],['Energieklasse','C, 625 kWh/Jahr'],['Glasflaschen 0,5 l','180'],['PET 0,5 l','180'],['Dosen 0,33 l','360'],['Produkte','Ø 57,6 bis 72,5 mm, H 116 bis 295 mm']],
  fits:'Glasflaschen-Konzepte, regionale Getränke.',
  pitch:'Glasflaschen und Pfand: passt zu Nachhaltigkeitszielen.',
  related:['narrow','flex'] },
{ id:'brain', cat:'vending', group:'Steuereinheit', brand:'SandenVendo', name:'Brain MMV', serie:'', img:'v_brain', configs:[['Brain Master Terminal MMV',5245]],
  sub:'Touch-Master für mehrere Automaten', price:5245, num:null, metric:'18,5" Touch', water:[], tags:['snack','drink','frozen','nonfood','indoor'],
  features:['18,5-Zoll-Touchscreen als zentrale Bedienung','Verbindet G-Snack, G-Drink, G-Snack Evolution, Locker und Frozen','Unbeaufsichtigter Verkauf rund um die Uhr','Perfekte Kontrolle, kosteneffizient'],
  specs:[['Maße H × B × T','1830 × 400 × 815 mm'],['Gewicht','105 kg'],['Display','Touchscreen 18,5"'],['Steuerung','Executive / MDB'],['Leistungsaufnahme','50 W'],['Elektroanschluss','220/240 V, 50/60 Hz']],
  fits:'Automatenwände, Mini-Markt im Betrieb.',
  pitch:'Ein Bildschirm, ein Bezahlsystem für die ganze Automatenwand.',
  related:['gsnack','locker','frozen'] },
{ id:'gsnackod', cat:'vending', group:'Snackautomat', brand:'SandenVendo', name:'G-Snack Outdoor', serie:'', img:'v_gsnackod', configs:[['SM6 OD Metall-Panel ohne / mit Lift','7.240 / 8.000 €'],['SM8 OD Metall-Panel ohne / mit Lift','7.990 / 8.600 €'],['SMX 10 OD ohne / mit Lift','8.100 / 8.990 €'],['ST 8 OD Touch ohne / mit Lift','8.480 / 9.000 €'],['STX 10 OD Touch ohne / mit Lift','9.100 / 9.640 €'],['Slave SS6 OD ohne / mit Lift','6.590 / 7.290 €'],['Slave SS8 OD ohne / mit Lift','6.890 / 7.550 €'],['Slave SSX 10 OD ohne / mit Lift','7.390 / 8.050 €']],
  sub:'Wetterfest mit Dach und beheiztem Glas', price:7240, num:70, metric:'bis 70 Auswahlen', water:[], tags:['snack','drink','outdoor'],
  features:['Regenschutz nach IP34, Dach','Beheiztes Glas','Schneller Produktlift','7-Zoll-Touchscreen','Betrieb von -15 bis +38 °C'],
  specs:[['Innentemperatur','+2 bis +18 °C'],['Umgebungstemperatur','-15 bis +38 °C'],['Display','Touchscreen 7"'],['Steuerung','Executive / MDB'],['Kühleinheit','HCD'],['Leistungsaufnahme','450 W'],['Energieklasse','E']],
  variants:{ cols:['STX OD · Ten','ST8 OD · Eight','ST6 OD · Six'], rows:[
    ['Maße H × B × T','1900 × 1200 × 1010','1900 × 1030 × 1010','1900 × 890 × 1010'],['Gewicht','400 kg','350 kg','325 kg'],
    ['Auswahlen pro Etage','10','8','6'],['Auswahlen','max. 70','max. 56','max. 42'],['Energie kWh/Jahr (Kat. 2)','1553','1232','1280'] ]},
  fits:'Firmengelände, Tankstellen, Campingplätze, Sportanlagen.',
  related:['gdrinkod','gsnack'] },
{ id:'gdrinkod', cat:'vending', group:'Getränkeautomat', brand:'SandenVendo', name:'G-Drink Outdoor', serie:'', img:'v_gdrinkod', configs:[['DM6 OD Metall-Panel',8240],['DM9 OD Metall-Panel',8640],['DT 6 OD Touch',8840],['DT9 OD Touch',9240]],
  sub:'Getränke draußen, rund um die Uhr', price:8240, num:63, metric:'bis 504 Dosen', water:[], tags:['drink','outdoor'],
  features:['Regenschutz nach IP34, Dach','Beheiztes Glas','7-Zoll-Touchscreen','Ergonomisches Design','Betrieb von -15 bis +38 °C'],
  specs:[['Innentemperatur','+2 bis +10 °C'],['Umgebungstemperatur','-15 bis +38 °C'],['Display','Touchscreen 7"'],['Steuerung','Executive / MDB'],['Leistungsaufnahme','490 W'],['Energieklasse','E']],
  variants:{ cols:['DT9 OD · G-Drink 9','DT6 OD · G-Drink 6'], rows:[
    ['Maße H × B × T','1875 × 1260 × 1010','1875 × 990 × 1010'],['Gewicht','410 kg','350 kg'],['Auswahlen','45 / max. 63','30 / max. 42'],
    ['Dosen 0,33 l','504','336'],['PET 0,5 l','360','240'],['Energie kWh/Jahr','1700','1290'] ]},
  fits:'Außenbereiche mit Getränkebedarf.',
  related:['gsnackod','gdrink'] },
{ id:'frozen', cat:'vending', group:'Tiefkühlautomat', brand:'SandenVendo', name:'G-Frozen', serie:'', img:'v_frozen', configs:[['G-Snack Frozen FF8 Touch ohne Lift',11840],['Frozen KF8 Slave',10950]],
  sub:'Tiefkühlautomat bis -25 °C', price:11840, num:40, metric:'bis 40 Auswahlen', water:[], tags:['frozen','indoor'],
  features:['Beheizte dreiteilige Glastür gegen Kondensation','Kaltlufteindämmung schützt den Produktbereich','Modulares Spiralsystem','Anti-Vandalismus-Rollladen','Touch-Bedienfeld, natürliches Kältemittel R290'],
  specs:[['Maße H × B × T','1830 × 1026 × 845 mm'],['Gewicht','360 kg'],['Etagen','5'],['Auswahlen','max. 40'],['Display','Touchscreen 7"'],['Kühleinheit','HC, R290'],['Innentemperatur','-10 bis -25 °C'],['Leistungsaufnahme','750 W'],['Klimaklasse','4 (+30 °C, 55 % r. F.)']],
  variants:{ cols:['FF8 · Doppelregal','FF8-S · Einzelregal'], rows:[['Auswahlen pro Etage','4+4','8'],['Geeignet für','Tiefkühlware in Standardgröße','sperrige Ware wie Eiswürfelboxen, große Pizzen']] },
  fits:'Eis im Sommer, Tiefkühlgerichte für Schichtbetrieb.',
  related:['brain','gsnack'] },
{ id:'gcaffe', cat:'vending', group:'Heißgetränkeautomat', brand:'SandenVendo', name:'G-Caffè Uni-Q Touch', serie:'', img:'v_gcaffe',
  sub:'Kaffeeautomat mit 18,5"-Touchscreen', price:null, num:22, metric:'22 Auswahlen', water:[], tags:['kaffee','indoor'],
  features:['18,5-Zoll-Touchscreen','LED-beleuchtete Front, ergonomisch auch für Rollstuhlfahrer','Flexibles Becherwerk 70 bis 73 mm (Option 80 mm)','Platz für bis zu 3 Zahlungssysteme','Master-Slave-Verbindung mit G-Snack'],
  specs:[['Maße H × B × T','1830 × 655 × 770 mm'],['Gewicht','180 kg'],['Becher','70 bis 73 mm: max. 750 · 80 mm: max. 550'],['Rührstäbchen','500 Stück'],['Auswahlen','22'],['Wasseranschluss','G 3/4", 2 bis 8 bar'],['Steuerung','MDB / Executive'],['Elektroanschluss','220 bis 240 V, 50/60 Hz'],['Bohnenbehälter','4,9 bis 5,1 kg']],
  variants:{ cols:['HS 7T · Espresso','HN 7T · Instant'], rows:[['Zutatenbehälter','6 × M (4,4 l)','8 × M (4,4 l)'],['Heizung','2.300 W Espresso + 3.200 W Pulver','3.200 W'],['Kaffeemühle','ja','nein']] },
  fits:'Öffentliche Bereiche, Kliniken, Schulen mit Becherkaffee.',
  related:['gsnack','barista500pro'] },
{ id:'locker', cat:'vending', group:'Locker', brand:'SandenVendo', name:'Matrix Locker', serie:'', img:'v_locker', configs:[['Locker Indoor DLCK 24',4600],['Locker Indoor DLCK 20',4750],['Locker Indoor DLCK 18',5020]],
  sub:'Fächerautomat für sperrige Artikel', price:4600, num:24, metric:'bis 24 Fächer', water:[], tags:['nonfood','indoor'],
  features:['Für Extra-Vending-Artikel, sperrige und unkonventionelle Produkte','Transparente Module, volle Produktsicht vor dem Kauf','Als Slave-Einheit an Master-Automaten anschließbar','Unbeaufsichtigter Verkauf rund um die Uhr'],
  specs:[['Maße H × B × T','1830 × 925 × 515 mm'],['Gewicht','300 kg'],['Auswahlen pro Etage','max. 4'],['Etagen','6'],['Auswahlen','max. 24'],['Leistungsaufnahme','50 W'],['Elektroanschluss','220 V / 50 Hz']],
  fits:'Arbeitsschutz, Werkzeug, Ersatzteile, Laborbedarf.',
  pitch:'Gibt Arbeitsschutz und Verbrauchsmaterial rund um die Uhr aus.',
  related:['brain'] }
];

/* ---------- Zubehör & Verbrauch pro Kategorie ---------- */
const EXTRAS = {
  wasser: { title:'Zubehör & Service', groups:[
    { h:'Service pro Monat', items:[['Water Care',39,'/ Monat'],['Water Care+',49,'/ Monat'],['Water Care Hot',55,'/ Monat'],['Water Care Hot+',69,'/ Monat']] },
    { h:'Zubehör und Add-ons', items:[['UVC-Entkeimung Wassereingang',320],['UVC LED am Auslass',210],['Unterschrank Blusoda 30',470],['Unterschrank Blusoda 45',470],['Portion Control Blusoda',297],['Unterschrank, mit oder ohne Ablauf'],['Erhöhung'],['Gaswarnmelder'],['Literzähler digital'],['Hydrostopper mit 2 Sensoren']] },
    { h:'Kohlensäure', items:[['CO₂ 0,75 kg',22],['CO₂ 2 kg',34],['CO₂ 6 kg',52]] },
    { h:'Reinigung', items:[['Desinfektionsmittel Cooler Protect',22],['ewatec Multicleaner 500 ml',16.39],['ewatec Mikrofasertuch',2.5]] },
    { h:'Gläser & Flaschen', items:[['Trinkglas 200 ml (6 Stück)',21],['Latte-Macchiato-Glas (6 Stück)',17.88],['Glaskaraffe 1 l',7.7],['Edelstahlflasche 800 ml',15.72],['Premium Kavo-Trinkflaschen, BPA-frei, mit Logo','ab 2,50 €'],['Glasflaschen, verschiedene Ausführungen','ab 3,50 €'],['Kavo-Trinkflaschen, BPA-frei','ab 5,50 €']] }
  ], note:'Bei der Installation weisen wir Ihre Mitarbeiter in die Reinigung und den Gasflaschen-Wechsel ein.' },
  bottle: { title:'Bottles & Service', groups:[
    { h:'Service pro Monat', items:[['Bottle Care',23,'/ Monat']] },
    { h:'Preis pro Bottle ewatec H2O', items:[['1 bis 9 Bottles',18.10],['10 bis 19 Bottles',14.10],['20 bis 39 Bottles',12.10],['ab 40 Bottles',10.10]] },
    { h:'Pfand', items:[['Pfand pro Bottle',7.5],['Bottlerack bei Palettenabnahme',500]] }
  ], note:'Pfand wird bei jedem Wechsel verrechnet.' },
  kaffee: { title:'Zubehör & Service', groups:[
    { h:'ewatec coffee care pro Monat', items:[['Coffee Care S',29,'/ Monat'],['Coffee Care M',39,'/ Monat'],['Coffee Care L',49,'/ Monat']] },
    { h:'Milch', items:[['Milchkühler 1 l Saeco Magic',184],['7,0 l Kühlschrank Edelstahltür (G100, G500, Magic M2)',1013],['7,0 l Kühlschrank Glasfront (G100, G500, Magic M2)',1134],['7,0 l Kühlschrank Glasfront mit Tassenwärmer',1607],['4,5 l Kühlschrank Glasfront G100/G500',1798],['4,5 l Kühlschrank Glasfront G700',1781],['3,5 + 3,5 l Dualmilk-Kühlschrank G500/G700',1423]] },
    { h:'Unterschränke', items:[['Unterschrank G100, 41 × 57 × 84,5 cm',382],['Unterschrank G100 ausgestattet mit Satzbehälter',533],['Unterschrank mit Ausstattung G300',684],['Unterschrank GS MasterBrew',962],['Unterschrank Vitro S1, vorbereitet für Münzprüfer',465],['Holzunterschrank eintürig 70 × 60 × 85 cm',1983],['Holzunterschrank doppeltürig 100 × 60 × 85 cm',2251]] },
    { h:'Kits', items:[['Tassenwärmer 2 Ebenen',749],['Tassenwärmer 3 Ebenen',952],['Wasserselbstversorgung 20 l Tank + Flowjet G500/G700',744],['Seitlicher Tank 5 l G100',294],['Kit Satzabwurf G100',102],['Kit Satzabwurf G300',76],['Kit Satzabwurf G500/G700',212],['Kit Abwasserfestanschluss G100',95],['Festwasserkit Vitro S1',144],['Ice Maker Modul',5682]] },
    { h:'Bezahlsysteme', items:[['Münzprüfer inkl. MDB-Kabel',292],['Münzwechsler SuzoHapp C2 MDB',545],['Geldscheinleser ICT X7P (5, 10, 20 €)',499],['Nayax Onyx, kontaktlos',429],['Chipsystem Hi!',550],['senvend UX700',1200],['Seitliches Bezahlmodul kontaktlos (Animo)',535],['Mini-Gehäuse für kontaktloses Bezahlen',155]] }
  ]},
  barista: { title:'Zubehör', groups:[ { h:'Zubehör', items:[['Tamper Ø 57 mm, exklusiv für G4/G6 · NT1042',17],['Q-Press Stamper, automatisch',993]] } ]},
  vending: { title:'Zubehör & Service', groups:[
    { h:'Service pro Monat', items:[['Vending Care',29,'/ Monat']] },
    { h:'Bezahlsysteme', items:[['Münzprüfer inkl. MDB-Kabel',292],['Münzwechsler SuzoHapp C2 MDB',545],['Geldscheinleser ICT X7P (5, 10, 20 €)',499],['Geldscheinleser ICT XBA (5 bis 50 €)',559],['Nayax Onyx, kontaktlos',429],['Einbaurahmen Nayax',70],['senvend UX700',1200],['Chipsystem Hi!',550],['Hi! Tischaufwerter',850],['Seco Karl4',798],['Anbaugehäuse Münzwechsler Cage 540 GW',720]] }
  ]}
};

/* ---------- Montage-Check Tafelwasser ---------- */
const CHECKLIST = [
  ['Wasseranschluss','8 mm Zulauf, Absperrhahn erreichbar. GWS: Eingangsdruck 2 bis 3 bar. Celli: Wasser-Druckminderer nicht im Lieferumfang.'],
  ['Strom','Normalgeräte 145 bis 530 W. MF 20 UPH 2.000 W, H2OMY IN 1.410 W. C-Tap und Power Stream brauchen eine Steckdose unter der Spüle.'],
  ['Filter','Celli extern in die Leitung. Blusoda und Cool1: Filter und Filterkopf separat. Wave Home: Filter in der Box.'],
  ['CO₂','6 mm Leitung. Celli: CO₂-Druckminderer nicht enthalten. Cool1: Flasche mit Halterung im Gerät. Wave Home: Flasche in der Box.'],
  ['Platz unter der Spüle','J-Class IN 25,5 × 40 × 40 cm, H2OMY IN 26 × 33 × 40,7 cm, Wave-Home-Box 21,6 × 47,9 × 44,1 cm. Celli kondensiert belüftet, Luft einplanen.'],
  ['Raumtemperatur','GWS min. 5 °C, max. 35 °C. Ungeheizte Hallen im Winter prüfen.']
];

/* ---------- Merksätze (nur Vertriebsmodus) ---------- */
const MERKSAETZE = {
  wasser:['Jedes Gerät der neuen Linie kann Sprudel.','Theke frei: Auftisch. Keine Theke: Standgerät. Spüle: Untertisch mit Hahn.','Heißwasser auf der Theke: MF 20 UPH. An der Spüle: H2OMY IN mit C-Tap oder Power Stream ACHWG.','Hähne laufen nur mit Untertischgerät, deshalb immer als Set anbieten.','Kantine oder Self-Service: Cool1 80.','Faustregel: Die Zahl im Gerätenamen ist die Kühlleistung in l/h.'],
  kaffee:['Tassen pro Tag entscheiden die Geräteklasse: bis 100 G100 oder Magic, bis 200 G300 oder G500, darüber G700 oder MasterBrew.','Self-Service mit Becher und Bezahlsystem: Barista-Standautomat.','Pulvermilch (G300) senkt Betriebskosten, Frischmilch (G500, G700) hebt die Qualität.','Coffee Care immer mit anbieten: S 29 €, M 39 €, L 49 € im Monat.'],
  barista:['Tall Cup fragen, sobald To-go-Becher im Spiel sind.','Zur Maschine gehört eine Mühle: G4 für normale, G6 für hohe Frequenz.','3-gruppig und GT7 3-gruppig Pot Mix: Stromanschluss vorab klären.'],
  vending:['Erst die Ware klären, dann den Automaten: Snack, Getränk, Tiefkühl, Kaffee oder Non-Food.','Draußen nur Outdoor-Modelle mit IP34, Dach und beheiztem Glas.','Mehrere Automaten: Brain MMV als gemeinsamer Touch-Master.']
};
const RATES = { 36:0.032197, 48:0.02533, 60:0.0214 };

const IMG_EXT = 'webp';
export default { PRICE_DATE, CATEGORIES, FILTERS, ADVISOR, PRODUCTS, EXTRAS, CHECKLIST, MERKSAETZE, RATES };
